[template]
src = "cloudwatch_exporter.yml.tmpl"
dest = "/etc/cloudwatch_exporter.yml"
prefix = "/%%PROJECT%%/%%ARENA%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/sbin/reload cloudwatch_exporter || /sbin/restart cloudwatch_exporter || /sbin/start cloudwatch_exporter"
