[template]
src = "cloudwatch_exporter_billing.yml.tmpl"
dest = "/etc/cloudwatch_exporter_billing.yml"
prefix = "/%%PROJECT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/sbin/reload cloudwatch_exporter_billing || /sbin/restart cloudwatch_exporter_billing || /sbin/start cloudwatch_exporter_billing"
