global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus'

rule_files:
  - "/etc/prometheus/rules.prom"
  - "/etc/prometheus/rules.d/*.prom"

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:80']

  - job_name: 'consul'
    relabel_configs:
    - source_labels: ['__meta_consul_address']
      regex:         '(.*)'
      target_label:  '__address__'
      replacement:   '$1:9107'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'

    consul_sd_configs:
    - server: 'localhost:8500'
      services:
        - consul

  - job_name: 'node'

    relabel_configs:
    - source_labels: ['__meta_consul_address']
      regex:         '(.*)'
      target_label:  '__address__'
      replacement:   '$1:9100'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'

    consul_sd_configs:
    - server: 'localhost:8500'
      services:
        - datadog
